### ISSUE TITLE
Thoughts on UI/UX

### ISSUE THREAD

**Issue by psaia** [psaia/di#1]
There are unsolved problems to figure out for the UX/UI. They are the following:

* Should we allow shapes/elements to change colors? If so, where and how do we indicate those settings?
* How do we indicate selected elements vs non-selected elements?
* Elements should should have "anchor" points in areas that are attachable or selectable. For example, the places where a line can connect to a rectangle. Or a place the user can click to change the size of a rectangle. Maybe we can only see these special anchor points when an element is active or when the cursor is over the shape?
* Do we include "move to front" and "move to back" functionality. Right now it can be doable by drag/dropping a layer in the layer sidebar.
* How should we handle the export options/menu?
* How should we handle the photo-to-vector functionality? I really love this feature and should try to bake it in.
* Should we change the name/logo? I'm not in love.
* For icons we could create a custom font with [IcoMoon](https://icomoon.io/app/#/select).

**Comment by lx7009** [comment]
1. I think we don't need to change colors for right now, but we could do it in the future.

2. With different color(like blue) or auxiliary line?

3. Anchor points for right now is not necessary, after talking with people who like to use diagram every day, they told me that don't need at all.

4. I think about it,  I think it's useful, if people click the right, it should have a menu about this function. if it's not too much job, we can try it? or maybe later, since we already have layers which could have the same function.

5. Just like we talked before, export a new web page.

6. This one is a plus, but we can try it later.

7. Lol, I think right now we don't need to worry about it. We met yesterday in the Coffee shop, I am glad you like the logo I designed and I really love the name "TXT" :).

8. I think I Monaco is great, I found this font in Visual Studio Code, which is an app for coding. Since the "TXT" is designed for software developers, I interview them and they said they like this font. How do you think about it?
